apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  selector:
  template:
    spec:
      containers:
      - name: myapp
        image: tomcat:11.0.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8088
