apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base

replicas:
- name: deployment
  count: 1

images:
- name: deployment
  newName: tomcat
  newTag: latest

ports:
- name: tx-app-port
  port:8088
  targetPort:80